---
- hosts: kubernetes-master-nodes
  become: true
  gather_facts: No
  vars_files:
  - ../env_variables

  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Restart kubeadm
    shell: kubeadm reset --force

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address {{ ad_addr }} --pod-network-cidr={{ cidr_v }}
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

#kubeadm init --apiserver-advertise-address 192.168.122.10 --pod-network-cidr=172.16.0.0/16